# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='t_shirt_size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
