# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_helper_t_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='reg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
